### ISSUE TITLE
AttributeError: 'Ollama' object has no attribute '_lc_kwargs'

### ISSUE THREAD

**Issue by sergiuionescu** [VinciGit00/Scrapegraph-ai#180]
**Describe the bug**
The current version of scrapegraph does not seem to be compatible with langchain==0.1.14 when trying to use the Ollama LLM.

**To Reproduce**
1. Dockerfile:
```
FROM  python:3.9.19

RUN mkdir -p /srv/app
COPY requirements.txt /srv/app

RUN pip install -r /srv/app/requirements.txt

WORKDIR /srv/app
```
2. docker-compose.yml:
```
version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_volume:/root/.ollama
    restart: unless-stopped

  scraper:
    build: .
    container_name: scraper
    volumes:
      - ./:/srv/app
    command:
      - /usr/local/bin/python
      - main.py

volumes:
  ollama_volume:
```

3. requirements.txt:
```
scrapegraphai==v0.10.0
```

4. main.py (from README.md):
```
from scrapegraphai.graphs import SmartScraperGraph

graph_config = {
    "llm": {
        "model": "ollama/mistral",
        "temperature": 0,
        "format": "json",  # Ollama needs the format to be specified explicitly
        "base_url": "http://localhost:11434",
        "_lc_kwargs": []
        # "model_tokens": 2000, # set context length arbitrarily
    },
}

smart_scraper_graph = SmartScraperGraph(
    prompt="List me all the articles",
    # also accepts a string with the already downloaded HTML code
    source="https://perinim.github.io/projects",  
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)
```

Result:
```
docker compose up scraper
[+] Running 1/1
 ✔ Container scraper  Recreated                                                                                                                                      0.4s 
Attaching to scraper
scraper  | Traceback (most recent call last):
scraper  |   File "/srv/app/main.py", line 14, in <module>
scraper  |     smart_scraper_graph = SmartScraperGraph(
scraper  |   File "/usr/local/lib/python3.9/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 47, in __init__
scraper  |     super().__init__(prompt, config, source)
scraper  |   File "/usr/local/lib/python3.9/site-packages/scrapegraphai/graphs/abstract_graph.py", line 47, in __init__
scraper  |     self.embedder_model = self._create_default_embedder(llm_config=config["llm"]
scraper  |   File "/usr/local/lib/python3.9/site-packages/scrapegraphai/graphs/abstract_graph.py", line 228, in _create_default_embedder
scraper  |     params = self.llm_model._lc_kwargs
scraper  | AttributeError: 'Ollama' object has no attribute '_lc_kwargs'
scraper exited with code 1
```

**Expected behavior**
The json containing the scraped data should be printed.
